### ISSUE TITLE
Add suport for phpmnd - PHP Magic Number Detector 

### ISSUE THREAD

**Issue by sasezaki** [DaveLiddament/sarb#95]
Hi.

feature request, it will be great if phpmnd support available.
https://github.com/povils/phpmnd

**Comment by DaveLiddament** [comment]
@sasezaki I should be able to get support for this sorted. Looks like the tool gives relative rather than absolute paths of files. However I am working on something that will enable support for relative paths. Once that is done I can add in support for this. Probably be about a week until this is supported. Hope that is OK?

**Comment by sasezaki** [comment]
Hi @DaveLiddament 

> However I am working on something that will enable support for relative paths. 

I had been to care it !

> Once that is done I can add in support for this. Probably be about a week until this is supported. Hope that is OK?

I'm not in a hurry so it's okay. Thank you!

**Comment by DaveLiddament** [comment]
@sasezaki I've finally got round to this. Sorry it took so long.
